name: Tests and benchmarks

on:
  pull_request:
  workflow_dispatch:

jobs:

  tests-and-benchmarks:
    uses: matter-labs/era-compiler-ci/.github/workflows/solc-test.yml@solc-latest
    secrets: inherit
